# BOUND: TARLAANALIZ_SSOT_v1_2_0.txt – canonical rules are referenced, not duplicated.
"""API v1 router exports — all routers consolidated under endpoints/."""

from src.presentation.api.v1.endpoints import (
    admin_audit_router,
    admin_payments_router,
    admin_pricing_router,
    auth_router,
    calibration_router,
    expert_portal_router,
    experts_router,
    fields_router,
    missions_router,
    parcels_router,
    payment_webhooks_router,
    payments_router,
    pilots_router,
    pricing_router,
    qc_router,
    results_router,
    sla_metrics_router,
    subscriptions_router,
    training_feedback_router,
    weather_block_reports_router,
    weather_blocks_router,
)

__all__ = [
    "admin_audit_router",
    "admin_payments_router",
    "admin_pricing_router",
    "auth_router",
    "calibration_router",
    "expert_portal_router",
    "experts_router",
    "fields_router",
    "missions_router",
    "parcels_router",
    "payment_webhooks_router",
    "payments_router",
    "pilots_router",
    "pricing_router",
    "qc_router",
    "results_router",
    "sla_metrics_router",
    "subscriptions_router",
    "training_feedback_router",
    "weather_block_reports_router",
    "weather_blocks_router",
]
